[package]
name = "towny"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.9.0", features = ["macros"] }
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
